---
    - name: install nginx & postgres
      hosts: all
      become: yes
      tasks: 
        - name: Uptade all packages
          ansible.builtin.apt:
            name: "*"
            state: latest
            update_cache: yes 
            force_apt_get: yes
        - name: Install nginx
          ansible.builtin.apt:
            name: nginx 
            state: latest
            update_cache: yes
        - name: start nginx
          service: 
            name: nginx 
            enabled: true 
            state: started
        - name: Install postgres
          ansible.builtin.apt:
            name: postgresql 
            state: latest
            update_cache: yes
        - name: start postgresql
          service: 
            name: postgresql 
            enabled: true 
            state: started